#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.Resource", IsApplication=true)]

namespace Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public const int black = 2131034117;
			
			// aapt resource value: 0x7f050033
			public const int blue_100 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int blue_200 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int blue_300 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int blue_400 = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int blue_50 = 2131034162;
			
			// aapt resource value: 0x7f050037
			public const int blue_500 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int blue_600 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int blue_700 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int blue_800 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int blue_900 = 2131034171;
			
			// aapt resource value: 0x7f050009
			public const int colorAccent = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int colorPrimary = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int colorPrimaryDark = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int gold = 2131034115;
			
			// aapt resource value: 0x7f050047
			public const int green_100 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int green_200 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int green_300 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int green_400 = 2131034186;
			
			// aapt resource value: 0x7f050046
			public const int green_50 = 2131034182;
			
			// aapt resource value: 0x7f05004b
			public const int green_500 = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int green_600 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int green_700 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int green_800 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int green_900 = 2131034191;
			
			// aapt resource value: 0x7f050004
			public const int grey = 2131034116;
			
			// aapt resource value: 0x7f050029
			public const int grey_100 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int grey_200 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int grey_300 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int grey_400 = 2131034156;
			
			// aapt resource value: 0x7f050028
			public const int grey_50 = 2131034152;
			
			// aapt resource value: 0x7f05002d
			public const int grey_500 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int grey_600 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int grey_700 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int grey_800 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int grey_900 = 2131034161;
			
			// aapt resource value: 0x7f05003d
			public const int indigo_100 = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int indigo_200 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int indigo_300 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int indigo_400 = 2131034176;
			
			// aapt resource value: 0x7f05003c
			public const int indigo_50 = 2131034172;
			
			// aapt resource value: 0x7f050041
			public const int indigo_500 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int indigo_600 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int indigo_700 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int indigo_800 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int indigo_900 = 2131034181;
			
			// aapt resource value: 0x7f050002
			public const int orange = 2131034114;
			
			// aapt resource value: 0x7f050051
			public const int orange_500 = 2131034193;
			
			// aapt resource value: 0x7f050015
			public const int pink_100 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int pink_200 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int pink_300 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int pink_400 = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int pink_50 = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int pink_500 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int pink_600 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int pink_700 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int pink_800 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int pink_900 = 2131034141;
			
			// aapt resource value: 0x7f050050
			public const int purple_500 = 2131034192;
			
			// aapt resource value: 0x7f05001f
			public const int red_100 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int red_200 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int red_300 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int red_400 = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int red_50 = 2131034142;
			
			// aapt resource value: 0x7f050023
			public const int red_500 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int red_600 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int red_700 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int red_800 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int red_900 = 2131034151;
			
			// aapt resource value: 0x7f050006
			public const int transparent = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int turquoise = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int yellow_100 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int yellow_200 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int yellow_300 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int yellow_400 = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int yellow_50 = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int yellow_500 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int yellow_600 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int yellow_700 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int yellow_800 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int yellow_900 = 2131034131;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int firstPage_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int firstPage_button2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int login_input = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int opencard_input = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int personal_bottom_border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int personal_linear = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int recharge_phone_number = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int recharge_price_card = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int recharge_submit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int start_screen = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_menu_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tab_menu_connection = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tab_menu_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tab_menu_text = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tab_menu_user = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int GridLayout1 = 2131230732;
			
			// aapt resource value: 0x7f080018
			public const int account = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int btn10 = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int btn100 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int btn1000 = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int btn20 = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int btn200 = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int btn2000 = 2131230741;
			
			// aapt resource value: 0x7f08000f
			public const int btn30 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int btn50 = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int btn500 = 2131230739;
			
			// aapt resource value: 0x7f080024
			public const int div_tab_bar = 2131230756;
			
			// aapt resource value: 0x7f08001b
			public const int forgetPassword = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int goRegest = 2131230748;
			
			// aapt resource value: 0x7f080017
			public const int imageView1 = 2131230743;
			
			// aapt resource value: 0x7f080001
			public const int line1 = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout1 = 2131230729;
			
			// aapt resource value: 0x7f080026
			public const int linearLayout2 = 2131230758;
			
			// aapt resource value: 0x7f08001a
			public const int login_btn = 2131230746;
			
			// aapt resource value: 0x7f080025
			public const int ly_content = 2131230757;
			
			// aapt resource value: 0x7f080020
			public const int ly_tab_bar = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int ly_top_bar = 2131230750;
			
			// aapt resource value: 0x7f080005
			public const int opencard_input_idcard = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int opencard_input_name = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int opencard_submit = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int opencard_text_idcard = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int opencard_text_name = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int opencard_text_number = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int password = 2131230745;
			
			// aapt resource value: 0x7f08000b
			public const int payamount = 2131230731;
			
			// aapt resource value: 0x7f080028
			public const int regist_getVCode = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int regist_vCode = 2131230759;
			
			// aapt resource value: 0x7f08001d
			public const int relativelayout1 = 2131230749;
			
			// aapt resource value: 0x7f080022
			public const int tab_openccard = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int tab_personal = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int tab_recharge = 2131230753;
			
			// aapt resource value: 0x7f080007
			public const int textView1 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int textView2 = 2131230730;
			
			// aapt resource value: 0x7f080016
			public const int tvPay = 2131230742;
			
			// aapt resource value: 0x7f080000
			public const int txt_content = 2131230720;
			
			// aapt resource value: 0x7f08001f
			public const int txt_topbar = 2131230751;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fg_content = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fg_openCard = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fg_personal = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fg_recharge = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Regist = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int arrow_right = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int arrow_right_small = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int connection = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int connection_fill = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Icon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int logo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int user = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int user_48 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int user_64 = 2130903048;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int firstPage_goLogin = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int firstPage_otherWay = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int firstPage_phone = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int firstPage_title = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int firstPage_wechat = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int forgetPassword = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int goRegest = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int login_account = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int login_btn = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int login_password = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int regist_btn = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int regist_getVCode = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int regist_password = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int regist_phone = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int regist_vCode = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int FirstAndroid = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Login = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Splash = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int login_input = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int openCardInput = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int openCardLabel = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int openCardLiner = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int personalLinear = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int priceCard = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
